export default[
	{
		name:'GitHub Pages',
		icon:{
			light:'https://mcbeeringi.github.io/img/icon.svg',
			dark:'https://mcbeeringi.github.io/img/icon.svg#!',
		},
		src:'/ghp',
		dst:'https://mcbeeringi.github.io/',
		code:301
	},
	{
		name:'HomePage',
		icon:{
			light:'https://mcbeeringi.dev/img/icon.svg',
			dark:'https://mcbeeringi.dev/img/icon.svg'
		},
		src:'/h',
		dst:'https://mcbeeringi.dev/',
		code:301
	},
	{
		name:'X(Twitter)',
		src:'/x',
		dst:'https://x.com/McbeEringi',
		code:301
	},
	{
		name:'GitHub',
		src:'/g',
		dst:'https://github.com/mcbeeringi',
		code:301
	},
	{
		name:'npm',
		src:'/n',
		dst:'https://npmjs.com/~mcbeeringi',
		code:301
	},
	{
		name:'misskey.io',
		src:'/m',
		dst:'https://misskey.io/@mcbeeringi',
		code:301
	},
	{
		name:'Qiita',
		src:'/q',
		dst:'https://qiita.com/mcbeeringi',
		code:301
	}
];
